fixtures:
  repositories:
    apache: https://github.com/puppetlabs/puppetlabs-apache.git
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    firewall: https://github.com/puppetlabs/puppetlabs-firewall
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    postgresql: https://github.com/puppetlabs/puppet-postgresql.git
    mysql: https://github.com/puppetlabs/puppetlabs-mysql.git
    ruby: https://github.com/puppetlabs/puppetlabs-ruby.git
    systemd: https://github.com/camptocamp/puppet-systemd.git
    selinux: https://github.com/voxpupuli/puppet-selinux.git
    chocolatey: https://github.com/puppetlabs/puppetlabs-chocolatey.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    selinux_core:
      repo: https://github.com/puppetlabs/puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
