AllCops:
  Exclude:
    # Ignore HTML related things
    - '**/*.erb'
    # Ignore vendored gems
    - 'vendor/**/*'
    # Ignore code from test fixtures
    - 'spec/fixtures/**/*'

Lint/ConditionPosition:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Style/SpaceBeforeComment:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

# DISABLED - not useful
Metrics/MethodLength:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/Eval:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/DefEndAlignment:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/Void:
  Enabled: true

Style/AccessModifierIndentation:
  Enabled: true

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AlignArray:
  Enabled: true

Style/AlignHash:
  Enabled: true

Style/AlignParameters:
  Enabled: true

Metrics/BlockNesting:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CaseIndentation:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Metrics/ClassLength:
  Enabled: false

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/Tab:
  Enabled: true

Style/SpaceBeforeSemicolon:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true

Style/SpaceInsideBrackets:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true

Style/LeadingCommentSpace:
  Enabled: true

Style/SpaceBeforeFirstArg:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/SpaceAfterSemicolon:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: true

Style/SpaceBeforeComma:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/CommentIndentation:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ConstantName:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: true

Style/DotPosition:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: true

Style/IndentArray:
  Enabled: true

Style/IndentHash:
  Enabled: true

Style/IndentationConsistency:
  Enabled: true

Style/IndentationWidth:
  Enabled: true

Style/EmptyLines:
  Enabled: true

Style/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/Next:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/VariableName:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/FileName:
  Enabled: false

Style/For:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/OpMethod:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Metrics/ParameterLists:
  Enabled: false

Lint/RequireParentheses:
  Enabled: true

Style/SpaceBeforeFirstArg:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Lint/Debugger:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/MultilineBlockLayout:
  Enabled: true

# These cops are enabled by default, they have been disabled to get started with Rubocop
# They should be re-evaluated soonish - rnelson0, 2/1/2016
Metrics/AbcSize:
  Enabled: False

Metrics/PerceivedComplexity:
  Enabled: False

Lint/UselessAssignment:
  Enabled: true
