---
Gemfile:
  optional:
    ':test':
      - gem: 'fakefs'
      - gem: 'zabbixapi'
spec/spec_helper.rb:
  mock_with: ':mocha'
  spec_overrides:
    - "require 'support/acceptance/supported_versions'"
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
.github/workflows/ci.yml:
  with:
    beaker_facter: 'zabbix_version:Zabbix:5.0,6.0,7.0'
    beaker_hypervisor: 'container_podman'
    unit_runs_on: 'cern-self-hosted'
