---
Gemfile:
  optional:
    ':test':
      - gem: 'fakefs'
      - gem: 'zabbixapi'
spec/spec_helper.rb:
  spec_overrides:
    - "require 'support/acceptance/supported_versions'"
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
.github/workflows/ci.yml:
  with:
    beaker_facter: 'zabbix_version:Zabbix:6.0,7.0'
    unit_runs_on: 'cern-self-hosted'
    acceptance_runs_on: 'ubuntu-2004-m'
