---
Gemfile:
  optional:
    ':test':
      - gem: 'fakefs'
      - gem: 'zabbixapi'
spec/spec_helper.rb:
  mock_with: ':mocha'
  spec_overrides:
    - "require 'support/acceptance/supported_versions'"
    - "require 'spec_helper_methods'"
spec/spec_helper_acceptance.rb:
  unmanaged: false
.github/workflows/ci.yml:
  pidfile_workaround: CentOS,Ubuntu
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
